export const SINNER_ID = 323

export const mockPlayer = {
  id: 323,
  name: 'Jannik Sinner',
  country: { name: 'Italy', code: 'IT' },
  ranking: 1,
  age: 24,
  height: '188 cm',
  weight: '76 kg',
  plays: 'Right-handed',
  turned_pro: 2018,
  photo: null,
}

export const mockLiveMatch = {
  id: 9001,
  status: 'live',
  tournament: { name: "Queen's Club Championships", category: 'ATP 500', surface: 'Grass', city: 'London', country: 'GB' },
  round: 'Final',
  date: '2026-06-21T14:00:00Z',
  players: {
    home: { name: 'Jannik Sinner', rank: 1, country: 'IT', isFavorite: true },
    away: { name: 'Carlos Alcaraz', rank: 2, country: 'ES' },
  },
  score: {
    sets: [[6, 4], [4, 6], [5, 4]],
    currentGame: { home: 'AD', away: '40' },
    server: 'home',
    inProgress: true,
  },
  stats: {
    aces:            [12, 7],
    doubleFaults:    [2,  3],
    winners:         [34, 29],
    unforcedErrors:  [18, 24],
    firstServeIn:    ['71%', '68%'],
    firstServeWon:   ['78%', '72%'],
    secondServeWon:  ['56%', '51%'],
    breakPointsConverted: ['3/5', '2/6'],
    totalPointsWon:  [112, 98],
    netApproaches:   ['8/10', '6/9'],
  },
  pointLog: [
    { set: 3, game: 10, score: '40-40', winner: 'home', type: 'winner', shot: 'Forehand' },
    { set: 3, game: 10, score: '40-AD', winner: 'away', type: 'unforcedError', shot: 'Backhand' },
    { set: 3, game: 10, score: 'AD-40', winner: 'home', type: 'ace', shot: 'Serve' },
  ],
}

export const mockUpcoming = [
  {
    id: 9010,
    status: 'scheduled',
    tournament: { name: 'Wimbledon', category: 'Grand Slam', surface: 'Grass', city: 'London', country: 'GB' },
    round: 'Round 1',
    date: '2026-06-30T11:00:00Z',
    players: {
      home: { name: 'Jannik Sinner', rank: 1, country: 'IT', isFavorite: true },
      away: { name: 'TBD', rank: null, country: '' },
    },
  },
  {
    id: 9011,
    status: 'scheduled',
    tournament: { name: 'Wimbledon', category: 'Grand Slam', surface: 'Grass', city: 'London', country: 'GB' },
    round: 'Round 2',
    date: '2026-07-03T13:00:00Z',
    players: {
      home: { name: 'Jannik Sinner', rank: 1, country: 'IT', isFavorite: true },
      away: { name: 'TBD', rank: null, country: '' },
    },
  },
]

export const mockRecentMatches = [
  {
    id: 8001,
    status: 'finished',
    tournament: { name: "Queen's Club Championships", category: 'ATP 500', surface: 'Grass', city: 'London', country: 'GB' },
    round: 'Semifinal',
    date: '2026-06-19T15:00:00Z',
    players: {
      home: { name: 'Jannik Sinner', rank: 1, country: 'IT', isFavorite: true },
      away: { name: 'Holger Rune', rank: 9, country: 'DK' },
    },
    score: { sets: [[6, 3], [7, 6]], tiebreaks: [null, 4], winner: 'home' },
    stats: {
      aces:           [9, 5],
      doubleFaults:   [1, 4],
      winners:        [28, 22],
      unforcedErrors: [14, 27],
      firstServeIn:   ['74%', '61%'],
      firstServeWon:  ['79%', '69%'],
      secondServeWon: ['58%', '48%'],
      breakPointsConverted: ['2/3', '0/4'],
      totalPointsWon: [89, 74],
    },
  },
  {
    id: 8002,
    status: 'finished',
    tournament: { name: "Queen's Club Championships", category: 'ATP 500', surface: 'Grass', city: 'London', country: 'GB' },
    round: 'Quarterfinal',
    date: '2026-06-18T13:30:00Z',
    players: {
      home: { name: 'Jannik Sinner', rank: 1, country: 'IT', isFavorite: true },
      away: { name: 'Frances Tiafoe', rank: 18, country: 'US' },
    },
    score: { sets: [[6, 2], [6, 4]], tiebreaks: [null, null], winner: 'home' },
    stats: {
      aces:           [7, 8],
      doubleFaults:   [2, 3],
      winners:        [22, 19],
      unforcedErrors: [11, 22],
      firstServeIn:   ['69%', '64%'],
      firstServeWon:  ['76%', '67%'],
      secondServeWon: ['54%', '49%'],
      breakPointsConverted: ['3/4', '0/3'],
      totalPointsWon: [74, 60],
    },
  },
  {
    id: 8003,
    status: 'finished',
    tournament: { name: 'Roland Garros', category: 'Grand Slam', surface: 'Clay', city: 'Paris', country: 'FR' },
    round: 'Final',
    date: '2026-06-08T14:00:00Z',
    players: {
      home: { name: 'Jannik Sinner', rank: 1, country: 'IT', isFavorite: true },
      away: { name: 'Rafael Nadal', rank: 5, country: 'ES' },
    },
    score: { sets: [[7, 5], [4, 6], [6, 2], [6, 3]], tiebreaks: [null, null, null, null], winner: 'home' },
    stats: {
      aces:           [4, 2],
      doubleFaults:   [3, 5],
      winners:        [48, 39],
      unforcedErrors: [27, 41],
      firstServeIn:   ['62%', '58%'],
      firstServeWon:  ['72%', '68%'],
      secondServeWon: ['51%', '47%'],
      breakPointsConverted: ['6/9', '2/11'],
      totalPointsWon: [168, 142],
    },
  },
]

export const mockTournaments = [
  {
    id: 1,
    name: 'Australian Open',
    category: 'Grand Slam',
    surface: 'Hard',
    city: 'Melbourne',
    country: 'AU',
    dates: '2026-01-13 — 2026-01-26',
    status: 'finished',
    prize: '$96M AUD',
    winner: 'Jannik Sinner',
  },
  {
    id: 2,
    name: 'Indian Wells Masters',
    category: 'Masters 1000',
    surface: 'Hard',
    city: 'Indian Wells',
    country: 'US',
    dates: '2026-03-04 — 2026-03-17',
    status: 'finished',
    prize: '$10.3M',
    winner: 'Carlos Alcaraz',
  },
  {
    id: 3,
    name: 'Miami Open',
    category: 'Masters 1000',
    surface: 'Hard',
    city: 'Miami',
    country: 'US',
    dates: '2026-03-19 — 2026-03-30',
    status: 'finished',
    prize: '$10.3M',
    winner: 'Jannik Sinner',
  },
  {
    id: 4,
    name: 'Monte-Carlo Masters',
    category: 'Masters 1000',
    surface: 'Clay',
    city: 'Monte Carlo',
    country: 'MC',
    dates: '2026-04-07 — 2026-04-13',
    status: 'finished',
    prize: '$6.3M',
    winner: 'Casper Ruud',
  },
  {
    id: 5,
    name: 'Madrid Open',
    category: 'Masters 1000',
    surface: 'Clay',
    city: 'Madrid',
    country: 'ES',
    dates: '2026-04-23 — 2026-05-04',
    status: 'finished',
    prize: '$9.8M',
    winner: 'Jannik Sinner',
  },
  {
    id: 6,
    name: 'Italian Open (Rome)',
    category: 'Masters 1000',
    surface: 'Clay',
    city: 'Rome',
    country: 'IT',
    dates: '2026-05-07 — 2026-05-18',
    status: 'finished',
    prize: '$8.4M',
    winner: 'Carlos Alcaraz',
  },
  {
    id: 7,
    name: 'Roland Garros',
    category: 'Grand Slam',
    surface: 'Clay',
    city: 'Paris',
    country: 'FR',
    dates: '2026-05-25 — 2026-06-08',
    status: 'finished',
    prize: '$53.5M',
    winner: 'Jannik Sinner',
  },
  {
    id: 8,
    name: "Queen's Club Championships",
    category: 'ATP 500',
    surface: 'Grass',
    city: 'London',
    country: 'GB',
    dates: '2026-06-15 — 2026-06-21',
    status: 'live',
    prize: '$3.2M',
    winner: null,
  },
  {
    id: 9,
    name: 'Halle Open',
    category: 'ATP 500',
    surface: 'Grass',
    city: 'Halle',
    country: 'DE',
    dates: '2026-06-15 — 2026-06-21',
    status: 'live',
    prize: '$2.7M',
    winner: null,
  },
  {
    id: 10,
    name: 'Wimbledon',
    category: 'Grand Slam',
    surface: 'Grass',
    city: 'London',
    country: 'GB',
    dates: '2026-06-29 — 2026-07-12',
    status: 'upcoming',
    prize: '$50M',
    winner: null,
  },
  {
    id: 11,
    name: 'Canadian Open (Montreal)',
    category: 'Masters 1000',
    surface: 'Hard',
    city: 'Montreal',
    country: 'CA',
    dates: '2026-08-03 — 2026-08-09',
    status: 'upcoming',
    prize: '$7.3M',
    winner: null,
  },
  {
    id: 12,
    name: 'Cincinnati Masters',
    category: 'Masters 1000',
    surface: 'Hard',
    city: 'Cincinnati',
    country: 'US',
    dates: '2026-08-10 — 2026-08-17',
    status: 'upcoming',
    prize: '$7.3M',
    winner: null,
  },
  {
    id: 13,
    name: 'US Open',
    category: 'Grand Slam',
    surface: 'Hard',
    city: 'New York',
    country: 'US',
    dates: '2026-08-24 — 2026-09-06',
    status: 'upcoming',
    prize: '$65M',
    winner: null,
  },
  {
    id: 14,
    name: 'Shanghai Masters',
    category: 'Masters 1000',
    surface: 'Hard',
    city: 'Shanghai',
    country: 'CN',
    dates: '2026-10-05 — 2026-10-12',
    status: 'upcoming',
    prize: '$8.8M',
    winner: null,
  },
  {
    id: 15,
    name: 'Paris Masters',
    category: 'Masters 1000',
    surface: 'Hard (Indoor)',
    city: 'Paris',
    country: 'FR',
    dates: '2026-10-26 — 2026-11-01',
    status: 'upcoming',
    prize: '$6.1M',
    winner: null,
  },
  {
    id: 16,
    name: 'ATP Finals',
    category: 'ATP Finals',
    surface: 'Hard (Indoor)',
    city: 'Turin',
    country: 'IT',
    dates: '2026-11-09 — 2026-11-16',
    status: 'upcoming',
    prize: '$15M',
    winner: null,
  },
]

export const mockRankings = [
  { rank: 1,  name: 'Jannik Sinner',     country: 'IT', points: 11200, isFavorite: true },
  { rank: 2,  name: 'Carlos Alcaraz',    country: 'ES', points: 9580 },
  { rank: 3,  name: 'Alexander Zverev',  country: 'DE', points: 7420 },
  { rank: 4,  name: 'Daniil Medvedev',   country: 'RU', points: 6790 },
  { rank: 5,  name: 'Casper Ruud',       country: 'NO', points: 5430 },
  { rank: 6,  name: 'Andrey Rublev',     country: 'RU', points: 4980 },
  { rank: 7,  name: 'Grigor Dimitrov',   country: 'BG', points: 4540 },
  { rank: 8,  name: 'Hubert Hurkacz',    country: 'PL', points: 4320 },
  { rank: 9,  name: 'Holger Rune',       country: 'DK', points: 3980 },
  { rank: 10, name: 'Tommy Paul',        country: 'US', points: 3750 },
]
